#!/usr/bin/env zsh

##!/usr/bin/sh

DOTFILES=$HOME/.dotfiles
STOW_FOLDERS="nvim,tmux,rofi,i3,alacritty,picom,polybar,networkmanager-dmenu,bin,zsh"
echo $DOTFILES

# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

popd
