#!/usr/bin/env zsh

DOTFILES=$HOME/.dotfiles
STOW_FOLDERS="nvim"
echo $DOTFILES

# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

stow -D vim
stow vim -t ~
popd
